#!/bin/bash
# Rebuilds the wasm emission kernels and regenerates WasmSimdData.hx
# (base64-embedded modules). Requires emscripten (emcc) — only needed
# when kernel.c changes; the generated haxe file is committed.
set -e
cd "$(dirname "$0")"

emcc -O3 -msimd128 kernel.c -o kernel-simd.wasm --no-entry -sSTANDALONE_WASM -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=33554432 -sMAXIMUM_MEMORY=268435456 -Wl,--export=meshPartF32
emcc -O3 kernel.c -o kernel-scalar.wasm --no-entry -sSTANDALONE_WASM -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=33554432 -sMAXIMUM_MEMORY=268435456 -Wl,--export=meshPartF32

SIMD_B64=$(base64 -i kernel-simd.wasm | tr -d '\n')
SCALAR_B64=$(base64 -i kernel-scalar.wasm | tr -d '\n')

cat > WasmSimdData.hx <<EOF
package clay.simd.wasm;

// Generated by build.sh — do not edit manually.
// Base64-encoded wasm modules (see kernel.c).

class WasmSimdData {

    public static inline var KERNEL_SIMD_B64:String = '$SIMD_B64';

    public static inline var KERNEL_SCALAR_B64:String = '$SCALAR_B64';

}
EOF

ls -la kernel-simd.wasm kernel-scalar.wasm WasmSimdData.hx
echo "OK"
